VERSION: 0.0.1
HOST: 127.0.0.1
PORT: 5002
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: file_storage
DB_USER: user
SECRET_KEY: secret
DB_PASSWORD: user
PROD: false
DEBUG: false
UPLOAD_FOLDER: '/home/user/Documents/uploader/upload_folder'